/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 26 10:14:49 UTC 2021
 */

package org.mockito.internal.invocation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.mockito.internal.invocation.Invocation;
import org.mockito.internal.invocation.MockitoMethod;
import org.mockito.internal.invocation.realmethod.RealMethod;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVFS = true, useJEE = true) 
public class Invocation_ESTest extends Invocation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(3223);
      MockitoMethod mockitoMethod0 = mock(MockitoMethod.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(mockitoMethod0).toString();
      doReturn(false).when(mockitoMethod0).isVarArgs();
      Object[] objectArray0 = new Object[4];
      objectArray0[0] = (Object) mockitoMethod0;
      objectArray0[1] = (Object) integer0;
      objectArray0[2] = (Object) mockitoMethod0;
      objectArray0[3] = (Object) mockitoMethod0;
      RealMethod realMethod0 = mock(RealMethod.class, new ViolatedAssumptionAnswer());
      Invocation invocation0 = new Invocation(integer0, mockitoMethod0, objectArray0, 0, realMethod0);
      MockitoMethod mockitoMethod1 = mock(MockitoMethod.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(mockitoMethod1).isVarArgs();
      RealMethod realMethod1 = null;
      Invocation invocation1 = new Invocation(invocation0, mockitoMethod1, objectArray0, 1, (RealMethod) null);
      invocation0.getArguments();
      invocation0.getMethod();
      invocation0.markVerifiedInOrder();
      try { 
        invocation1.callRealMethod();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.mockito.internal.invocation.Invocation", e);
      }
  }
}
